version: "3"
services:
  nginx: # 服务名称，用户自定义
    image: nginx:latest  # 镜像版本
    ports:
      - 80:80  # 暴露端口
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    volumes: # 挂载
      - /pomonitor/nginx/html:/usr/share/nginx/html
      - /pomonitor/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true # 这个必须要，解决nginx的文件调用的权限问题
  mysql:
    image: mysql:5.7.38
    ports:
      - 3326:3306
    environment: # 指定用户root的密码
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Shanghai
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    volumes:
      - /pomonitor/mysql/data:/var/lib/mysql
      - /pomonitor/mysql/conf/my.cnf:/etc/mysql/my.cnf
      - /pomonitor/mysql/log:/var/log/mysql
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - /pomonitor/redis/data:/data
      - /pomonitor/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
  es:
    image: elasticsearch:7.6.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      # 单节点
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2G -Xmx2G
      - TZ=Asia/Shanghai
      - xpack.security.enabled=true
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic123
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail -u elastic:elastic123 localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /pomonitor/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /pomonitor/elasticsearch/data:/usr/share/elasticsearch/data
      - /pomonitor/elasticsearch/plugins:/usr/share/elasticsearch/plugins
  scrapy:
    image: scrapy:latest
    build:
      context: ./scrapy
      dockerfile: Dockerfile
    ports:
      - 7787:7787
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    volumes:
      - /pomonitor/scrapy:/code
    depends_on:
      es:
        condition: service_healthy
  pomonitor:
    image: pomonitor:latest
    build: . # 表示以当前目录下的Dockerfile开始构建镜像
    ports:
      - 7788:7788
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    volumes:
      - /pomonitor/conf:/conf
    depends_on: # 依赖与mysql、redis，其实可以不填，默认已经表示可以
      - mysql
      - redis
      - es
      - scrapy