spring:
  # 修改设置MySQL服务器地址和用户名及密码
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://hwnode1:63306/pomonitor?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: 123456hm


  # 修改设置Redis服务器地址
  redis:
    database: 0
    host: hwnode1
    port: 16379
    max-active: 10000
    max-idle: 10
    max-wait: 100000
    timeout: 100000

  #邮箱基本配置
  mail:
    protocol: smtps
    #配置smtp服务主机地址
    # qq邮箱为smtp.qq.com          端口号465或587
    # sina    smtp.sina.cn
    # aliyun  smtp.aliyun.com
    # 163     smtp.163.com       端口号465或994
    host: smtp.163.com
    #发送者邮箱
    username: yitian_hm@163.com
    #配置密码,注意不是真正的密码，而是刚刚申请到的授权码
    password: XNFJNIWXHJVKXWMD
    #端口号465或587
    port: 994
    #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

  elasticsearch:
    rest:
      uris: hwnode1:9200
      connection-timeout: 3000        #连接超时时间
      read-timeout: 10000              #读取超时时间
      username: elastic
      password: 07122201hm



# mybatis-plus相关配置
mybatis-plus:
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#定时任务线程池配置
scheduled-pool:
  executor-config:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 10
    keep-alive-time: 60

logging:
  level:
    com.stonedt.intelligence.dao : debug
    org:
      springframework:
        data:
          elasticsearch:
            core: debug
system:
  config:
    jwtKey: nobugxixihaha
    jwtFailureTime: 3600000
    aesKey: ABCDEFGHIJKL_key
    aesIv: ABCDEFGHIJKLM_iv
    aesAlgorithmstr: AES/CBC/PKCS5Padding